baseURL = "/"
languageCode = "en-us"
title = "The Encryption Compendium"
publishDir = "./public"
resourceDir = "./resources"

[params]
    description = "The encryption literature database"
    github = "https://github.com/The-Encryption-Compendium/TECv2"
    twitter = "https://twitter.com/SiliconFlatiron"

    # Development parameters
    use_development_vue_js = false

[taxonomies]
    tag = "tags"
