name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show configuration
        run: |
          echo "Hugo version: $(hugo version)"
          echo "Python version: $(python --version)"
          echo "------------------------"
          echo "Hugo configuration:"
          hugo config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r deploy_tools/requirements.txt

      - name: Build
        run: |
          python -m deploy_tools.generate_compendium data/data.bib
          mkdir public
          hugo --minify
          cp -r deploy_tools/additional_files/* public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: The-Encryption-Compendium/the-encryption-compendium.github.io
          publish_branch: master
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
